version: '3.5'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
volumes:
    postgres: